### ISSUE TITLE
Problem running locally

### ISSUE THREAD

**Issue by podviaznikov** [open-company/open-company-web#43]
I followed the instructions in the readme but got error after running `lein figwheel`:

```
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: dev
Compiling "resources/public/js/compiled/open_company.js" from ["src"]...
Compiling "resources/public/js/compiled/open_company.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:src/open_company_web/lib/devcards.cljs
 at clojure.core$ex_info.invoke (core.clj:4593)
Caused by: clojure.lang.ExceptionInfo: No such namespace: devcards.core, could not locate devcards/core.cljs, devcards/core.cljc, or Closure namespace "devcards.core"
 at clojure.core$ex_info.invoke (core.clj:4593)

clojure.lang.ExceptionInfo: No such namespace: devcards.core, could not locate devcards/core.cljs, devcards/core.cljc, or Closure namespace "devcards.core" {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:562)
	at cljs.analyzer$error.invoke(analyzer.cljc:560)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1668)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2504)
	at cljs.analyzer$analyze_STAR_$fn__2094.invoke(analyzer.cljc:2585)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
	at clojure.core$reduce.invoke(core.clj:6518)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2585)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2600)
	at cljs.analyzer$analyze_file$fn__2145.invoke(analyzer.cljc:2844)
	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:2839)
	at figwheel_sidecar.repl$analyze_build.invoke(repl.clj:242)
	at figwheel_sidecar.repl$analyze_builds.invoke(repl.clj:247)
	at figwheel_sidecar.repl$run_autobuilder_helper.invoke(repl.clj:295)
	at figwheel_sidecar.repl$start_autobuild.invoke(repl.clj:366)
	at figwheel_sidecar.repl$run_autobuilder.invoke(repl.clj:576)
	at user$eval16475.invoke(form-init8571742883165147213.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Subprocess failed
```

Any ideas what might happen?

**Comment by podviaznikov** [comment]
```
lein --version
Leiningen 2.5.3 on Java 1.8.0_25 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by bago2k4** [comment]
Yes the README was out of date. There is an alias for quick figwheel launch now, just run:
```console
lein figwheel!
```
or use the longer form:
```console
with-profile +devcards figwheel
```
README is updated too now.

**Comment by belucid** [comment]
@podviaznikov I also updated the README to mention that you need to be running the 2 other services for local usage/development.

**Comment by podviaznikov** [comment]
Thanks, was able to run it locally. Do I need to have Slack to try product or there is some workaround?

**Comment by belucid** [comment]
@podviaznikov We'll document a work around some time today.

**Comment by podviaznikov** [comment]
@belucid any updates?
